"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import dj_database_url
from dotenv import load_dotenv
import os 

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Простой подход через ISPROD
is_prod = os.environ.get('ISPROD', '0') == '1'

if is_prod:
    # Продакшен режим
    DEBUG = False
    ALLOWED_HOSTS = ['gir.generacia.energy']
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me-in-production')
else:
    # Локальная разработка
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    SECRET_KEY = "dev-secret-key-change-in-production"

# DB
DATABASES = {
    "default": dj_database_url.config(
        env="DATABASE_URL",
        default="postgres://appuser:strong_password@127.0.0.1:5432/appdb",
        conn_max_age=600,
        ssl_require=os.environ.get("DB_SSL_REQUIRE", "0") == "1",
    )
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True

INSTALLED_APPS = [
    "jazzmin", # admin panel
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "gir",

    # third-party
    "rest_framework",
    "corsheaders",

    # local
    "core",
]
AUTH_USER_MODEL = "gir.User"

# Простой подход через ISPROD
if is_prod:
    # Продакшен - используем whitenoise
    MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",  # только для продакшена
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
else:
    # Локальная разработка - Django сам раздает статику
    MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# DRF (минимум)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",              # для админки
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",        # <-- добавили JWT
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS/CSRF настройки
if is_prod:
    CORS_ALLOWED_ORIGINS = ['https://gir.generacia.energy']
    CSRF_TRUSTED_ORIGINS = ['https://gir.generacia.energy']
else:
    CORS_ALLOWED_ORIGINS = ['http://localhost:3000']
    CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'GET',        # чтение данных
    'POST',       # создание (если нужно)
    'OPTIONS',    # обязателен для CORS
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "uk"
TIME_ZONE = "Europe/Kiev"
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static/Media (разная раздача в dev/prod)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Статические файлы - папка опциональна
STATICFILES_DIRS = []
if (BASE_DIR / "static").exists():
    STATICFILES_DIRS.append(BASE_DIR / "static")

# Дополнительные настройки whitenoise для продакшена
if is_prod:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Генерація — Адмін",
    "site_header": "Генерація",
    "site_brand": "Генерація",
    "welcome_sign": "Ласкаво просимо 👋",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "copyright": "Генерація",
    "site_logo": None,
    "topmenu_links": [
        {"name": "Домівка", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API Health", "url": "/api/health/"},
    ],
}

# Убираем JAZZMIN_UI_TWEAKS - он не нужен и вызывает ошибки

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # <-- добавили
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

LOGIN_URL = '/login/'