# Generated by Django 5.0.7 on 2025-08-13 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE gir_user DROP COLUMN IF EXISTS company;",
            reverse_sql="ALTER TABLE gir_user ADD COLUMN company VARCHAR(200);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_user DROP COLUMN IF EXISTS phone;",
            reverse_sql="ALTER TABLE gir_user ADD COLUMN phone VARCHAR(20);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_user ALTER COLUMN email TYPE VARCHAR(254);",
            reverse_sql="ALTER TABLE gir_user ALTER COLUMN email TYPE VARCHAR(254);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_user ALTER COLUMN first_name TYPE VARCHAR(150);",
            reverse_sql="ALTER TABLE gir_user ALTER COLUMN first_name TYPE VARCHAR(150);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_user ALTER COLUMN last_name TYPE VARCHAR(150);",
            reverse_sql="ALTER TABLE gir_user ALTER COLUMN last_name TYPE VARCHAR(150);"
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS gir_frontenduser (
                id BIGSERIAL PRIMARY KEY,
                company VARCHAR(200),
                phone VARCHAR(20),
                photo VARCHAR(100),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                user_id INTEGER NOT NULL UNIQUE REFERENCES gir_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS gir_frontenduser;"
        ),
    ]
