# Generated by Django 5.0.7 on 2025-08-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва групи')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Група налаштувань',
                'verbose_name_plural': 'Групи налаштувань',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва налаштування')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
                ('setting_type', models.CharField(choices=[('single', 'Одиночне значення'), ('list', 'Список значень')], max_length=20, verbose_name='Тип налаштування')),
                ('value', models.TextField(blank=True, verbose_name='Значення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gir.settinggroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Значення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='gir.setting', verbose_name='Налаштування')),
            ],
            options={
                'verbose_name': 'Значення налаштування',
                'verbose_name_plural': 'Значення налаштувань',
                'ordering': ['setting', 'order', 'value'],
            },
        ),
    ]
