# Generated by Django 5.0.7 on 2025-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0002_remove_user_company_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="COMMENT ON TABLE gir_user IS 'Адміністратор';",
            reverse_sql="COMMENT ON TABLE gir_user IS NULL;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS user_id;",
            reverse_sql="ALTER TABLE gir_frontenduser ADD COLUMN user_id INTEGER REFERENCES gir_user(id);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD COLUMN IF NOT EXISTS email VARCHAR(254);",
            reverse_sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS email;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD COLUMN IF NOT EXISTS first_name VARCHAR(200);",
            reverse_sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS first_name;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;",
            reverse_sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS is_active;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD COLUMN IF NOT EXISTS last_name VARCHAR(200);",
            reverse_sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS last_name;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD COLUMN IF NOT EXISTS password VARCHAR(128) DEFAULT 'ChangeMe123!';",
            reverse_sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS password;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD COLUMN IF NOT EXISTS username VARCHAR(150) DEFAULT 'ChangeMe123!' UNIQUE;",
            reverse_sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS username;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ADD CONSTRAINT IF NOT EXISTS gir_frontenduser_email_unique UNIQUE (email);",
            reverse_sql="ALTER TABLE gir_frontenduser DROP CONSTRAINT IF EXISTS gir_frontenduser_email_unique;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ALTER COLUMN photo TYPE VARCHAR(100);",
            reverse_sql="ALTER TABLE gir_frontenduser ALTER COLUMN photo TYPE VARCHAR(100);"
        ),
    ]
