# Generated by Django 5.0.7 on 2025-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0002_remove_user_company_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontenduser',
            options={'verbose_name': 'Покупець', 'verbose_name_plural': 'Покупці'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Адміністратор', 'verbose_name_plural': 'Адміністратори'},
        ),
        migrations.RemoveField(
            model_name='frontenduser',
            name='user',
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='password',
            field=models.CharField(default='ChangeMe123!', max_length=128, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='username',
            field=models.CharField(default='ChangeMe123!', max_length=150, unique=True, verbose_name='Логін'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser ALTER COLUMN photo TYPE VARCHAR(100);",
            reverse_sql="ALTER TABLE gir_frontenduser ALTER COLUMN photo TYPE VARCHAR(100);"
        ),
    ]
