# Generated by Django 5.0.7 on 2025-08-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0003_alter_frontenduser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="COMMENT ON TABLE gir_frontenduser IS 'Користувач';",
            reverse_sql="COMMENT ON TABLE gir_frontenduser IS NULL;"
        ),
    ]
