# Generated by Django 5.0.7 on 2025-08-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0004_alter_frontenduser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenduser',
            name='photo',
        ),
    ]
