# Generated by Django 5.0.7 on 2025-08-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0004_alter_frontenduser_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE gir_frontenduser DROP COLUMN IF EXISTS photo;",
            reverse_sql="ALTER TABLE gir_frontenduser ADD COLUMN photo VARCHAR(100);"
        ),
    ]
