# Generated by Django 5.0.7 on 2025-08-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Найменування')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Од.вим')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Облікова ціна б.г. з ПДВ $')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Гуртова ціна з ПДВ, авт% $')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('modules_count', models.IntegerField(blank=True, null=True, verbose_name='Кількість модулів')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Вільно на складі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gir.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='gir_product_title_cd0385_idx'), models.Index(fields=['sku'], name='gir_product_sku_af3095_idx'), models.Index(fields=['category'], name='gir_product_categor_e5e9b6_idx')],
            },
        ),
    ]
