# Generated by Django 5.0.7 on 2025-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='Посилання'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL товара'),
        ),
    ]
