# Generated by Django 5.0.7 on 2025-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0008_product_description_product_external_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва імпорту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sheet_name', models.CharField(blank=True, max_length=255, verbose_name='Назва вкладки')),
                ('process_all_sheets', models.BooleanField(default=True, verbose_name='Обробити всі вкладки')),
                ('field_mapping', models.JSONField(default=dict, help_text='JSON з маппінгом полів Excel → Django', verbose_name='Маппінг полів')),
                ('skip_empty_rows', models.BooleanField(default=True, verbose_name='Пропускати порожні рядки')),
                ('create_categories', models.BooleanField(default=True, verbose_name='Створювати категорії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Шаблон імпорту',
                'verbose_name_plural': 'Шаблони імпорту',
                'ordering': ['name'],
            },
        ),
    ]
