# Generated by Django 5.0.7 on 2025-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0009_importtemplate'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE gir_product ALTER COLUMN url TYPE VARCHAR(255);",
            reverse_sql="ALTER TABLE gir_product ALTER COLUMN url TYPE VARCHAR(255);"
        ),
    ]
