# Generated by Django 5.0.7 on 2025-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0009_importtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL товара'),
        ),
    ]
