# Generated by Django 5.0.7 on 2025-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0010_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
