# Generated by Django 5.0.7 on 2025-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0011_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, max_length=500, verbose_name='URL товара'),
        ),
    ]
