# Generated by Django 5.0.7 on 2025-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0011_user_phone'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE gir_product ALTER COLUMN url TYPE VARCHAR(500);",
            reverse_sql="ALTER TABLE gir_product ALTER COLUMN url TYPE VARCHAR(500);"
        ),
    ]
