# Generated by Django 5.0.7 on 2025-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gir', '0012_increase_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Посилання'),
        ),
    ]
